POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ind0dXJuZXIiLCJpZCI6IjYyNTg0NTYxNDdiMTQ5OTU2ZWY1ZDA5MiIsImlhdCI6MTY0OTk1MjE0NCwiZXhwIjoxNjQ5OTU1NzQ0fQ.ypaT7-C7VEKaCwE-2kxPdG64-JHTz1kojYiK6WJdhco

{
  "title": "TDD Harms Architecture",
  "author": "Robert C. Martin",
  "url": "http://randomblog.com/tdd-harm",
  "likes": 17
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY2siLCJpZCI6IjYyNTgyYjEyY2UwNmU5OWU4MDM3NDRiYSIsImlhdCI6MTY0OTk1NTgyNCwiZXhwIjoxNjQ5OTU5NDI0fQ.35OHHx--uFpy5x_KzzLQVrWk0qA_-CSER62tQrrqOJE

{
  "title": "Minimum Spanning Tree",
  "author": "Kruskal",
  "url": "http://randomblog.com/krus-mst",
  "likes": 5
}