POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "jack",
    "password": "ihatebarbossa",
    "name": "Jack Sparrow"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "wturner",
    "password": "bootstrap",
    "name": "William Turner"
}